### ISSUE TITLE
想请教个问题

### ISSUE THREAD

**Issue by sh1luo** [miRemid/bililive-go#1]
最近看了你的B站视频，也在学习使用qamel，构建应用的时候遇到点问题，想请教一下。
想跑起来官方的helloworld 。但是一直报这个错、

ps:qtest目录下就是官方的main.go main.qml了。都是一模一样的。
而且我看了一下 我本地目录和官方github仓库中都确实没有这个makefile文件，不知道什么情况。
感谢！

```
E:\桌面\qtest>qamel build -p qtest
Starting build process.

Load config file...done
Removing old build files...done
Generating binding files...
Failed to create cgo file: failed to create cgo flags: open F:\Go_WorkSpace\src\github.com\go-qamel\qamel\qamel.makefile.Release: The system cannot find the file specified.
```

**Comment by miRemid** [comment]
请问有没有预先配置qamel，如果没有请配置一下，具体按照官方wiki

**Comment by sh1luo** [comment]
现在一直报这个错误。。。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "KamiR"<notifications@github.com&gt;; 
发送时间: 2020年3月7日(星期六) 晚上6:57
收件人: "miRemid/bililive-go"<bililive-go@noreply.github.com&gt;; 
抄送: "狙机手"<690898835@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [miRemid/bililive-go] 想请教个问题 (#1)




请问有没有预先配置qamel，如果没有请配置一下，具体按照官方wiki

**Comment by sh1luo** [comment]
对了 刚才忘了说了 配置了qamel。如图：







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"KamiR"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月7日(星期六) 晚上6:57
收件人:&nbsp;"miRemid/bililive-go"<bililive-go@noreply.github.com&gt;;
抄送:&nbsp;"狙机手"<690898835@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [miRemid/bililive-go] 想请教个问题 (#1)




请问有没有预先配置qamel，如果没有请配置一下，具体按照官方wiki

**Comment by miRemid** [comment]
图没有刷出来。。

**Comment by sh1luo** [comment]
....方便加一下你即时通讯联系吗？我是一名大二在校生，在开发一个工具，想请教点问题，感谢！
另外再发一下图...







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "KamiR"<notifications@github.com&gt;; 
发送时间: 2020年3月7日(星期六) 晚上7:00
收件人: "miRemid/bililive-go"<bililive-go@noreply.github.com&gt;; 
抄送: "狙机手"<690898835@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [miRemid/bililive-go] 想请教个问题 (#1)




图没有刷出来。。
